version: 2.1

jobs:
  nose-2_7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install docopt six nose
      - run: make test

  nose-3_5:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run make test

  nose-3_6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run make test

  nose-3_7:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run make test

  install-2_7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: python setup.py install
      - run: mackup --help

  install-3_5:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: python setup.py install
      - run: mackup --help

  install-3_6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: python setup.py install
      - run: mackup --help

  install-3_7:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: python setup.py install
      - run: mackup --help

  flake8-2_7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8

  flake8-3_5:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run flake8

  flake8-3_6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run flake8

  flake8-3_7:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run flake8

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .

  black:
    docker:
      - image: python
    steps:
      - checkout
      - run: pip install black
      - run: black --check --target-version py27 .

workflows:
  version: 2
  mackup:
    jobs:
      - nose-2_7
      - nose-3_5
      - nose-3_6
      - nose-3_7
      - install-2_7
      - install-3_5
      - install-3_6
      - install-3_7
      - flake8-2_7
      - flake8-3_5
      - flake8-3_6
      - flake8-3_7
      - mdl
      - black
